name: Build, Push and Deploy

on:
  push:
    branches: [main]

env:
  REGISTRY: cr.yandex
  REPO_ID: crppqi6tfv23hnubsg5t  # Идентификатор реестра (например, crp12345)
  IMAGE_NAME: demo_app
  K8S_NAMESPACE: default

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Аутентификация в Yandex Container Registry
    - name: Login to Yandex CR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: json_key
        password: ${{ secrets.YC_SA_KEY }}  # Ключ сервисного аккаунта

    # Сборка и публикация образа
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.REPO_ID }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.REGISTRY }}/${{ env.REPO_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy-to-k8s:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Настройка доступа к Kubernetes кластеру
    - name: Configure K8s
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG_DATA }}  # Закодированный base64 kubeconfig

    # Обновление образа в кластере
    - name: Deploy
      run: |
        kubectl -n ${{ env.K8S_NAMESPACE }} set image deployment/app-deployment \
        app-demo=${{ env.REGISTRY }}/${{ env.REPO_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
        --record
