name: Build, Push and Deploy

on:
  push:
    branches: [main]
  
#  release:
#    types: [created]

env:
  CR_REGISTRY: crppqi6tfv23hnubsg5t
  CR_REPO: demo_app
  IMAGE_TAG: ${{ github.sha }}
  K8S_NAMESPACE: default

jobs:
  build-and-push:
    environment: dev
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Yandex Cloud CR "Login" Action for GitHub Actions
          id: login-cr
          uses: yc-actions/yc-cr-login@v3
          with:
            yc-sa-json-credentials: ${{ secrets.YC_SA_KEY }}
        - name: Build, tag, and push image to Yandex Cloud Container Registry
          run: |
            docker build -t cr.yandex/$CR_REGISTRY/$CR_REPO:$IMAGE_TAG .
            docker push cr.yandex/$CR_REGISTRY/$CR_REPO:$IMAGE_TAG
  deploy-to-k8s:
    environment: dev
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Настройка доступа к Kubernetes кластеру
    - name: Configure K8s
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG_DATA }}  # Закодированный base64 kubeconfig

    # Обновление образа в кластере
    - name: Deploy
      run: |
        kubectl -n ${{ env.K8S_NAMESPACE }} set image deployment/app-deployment app-demo=cr.yandex/$CR_REGISTRY/$CR_REPO:$IMAGE_TAG
